using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Informix.Net.Core;

namespace ISL
{
    /// <summary>
    /// Interaction logic for AllUserDetails.xaml
    /// </summary>
    public partial class AllUserDetails : Window
    {
        IfxConnection con;
        IfxDataAdapter adpt;
        DataSet dataSet;

        IfxCommandBuilder ifxCommandBuilder;
        //Connection String
        string cs = "DataBase=logindb;Server=ol_informix1410_9;User ID = informix; Password=Rinvoke1;";

        string userName;

        public AllUserDetails()
        {
            InitializeComponent();
        }

        public AllUserDetails(string name)
        {
            InitializeComponent();
            userName = name;
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            loadData();
        }

        private void loadData()
        {
            con = new IfxConnection(cs);
            con.Open();

            adpt = new IfxDataAdapter("select userid, username, firstname, lastname, email, address, usertype from user", con);
            dataSet = new DataSet();
            adpt.Fill(dataSet, "user_details");
            dataGrid.ItemsSource = dataSet.Tables[0].AsDataView();
            TextBlockName.Text = userName;

            con.Close();
        }

        private void Save_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                ifxCommandBuilder = new IfxCommandBuilder(adpt);
                adpt.Update(dataSet, "user_details");
                //TextBlockName.Text = "pratishtha";
                //MessageBox.Show("record updated");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);

            }
        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }

        private void Logout_Click(object sender, RoutedEventArgs e)
        {
            MainWindow login = new MainWindow();
            login.Show();
            Close();
        }

        private void AddUser_Click(object sender, RoutedEventArgs e)
        {
            AddNewUserFromAdmin addNewUserFromAdmin = new AddNewUserFromAdmin();
            addNewUserFromAdmin.Show();
        }

        private void Refresh_Click(object sender, RoutedEventArgs e)
        {
            loadData();
        }
    }
}
